server {
  listen 80 default_server;
  server_name _;

  root /usr/share/nginx/site;
  index index.html index.htm;

  # Cache agressivo para assets versionados (Angular emite hash em nome de arquivo)
  location ~* \.(?:css|js|woff2?|ttf|otf|eot|svg|png|jpg|jpeg|gif|webp|ico)$ {
    expires 1y;
    access_log off;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  # APK não-versionado: sem cache
  location ~* \.apk$ {
    add_header Cache-Control "no-store, no-cache, must-revalidate";
    add_header Content-Disposition "attachment";
    try_files $uri =404;
  }

  # SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Healthcheck simples
  location = /healthz {
    access_log off;
    return 200 "ok\n";
    add_header Content-Type text/plain;
  }
}
